language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c travis.phpunit.xml
